name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache-folder: 'emsdk-cache'

      - name: Inject Sentry scripts
        run: |
          sed -i '/{{{ SCRIPT }}}/i\
          <script>\
            window.sentryOnLoad = function () {\
              Sentry.init({\
                dsn: "${{ secrets.SENTRY_DSN }}",\
                sendDefaultPii: true,\
                integrations: [Sentry.wasmIntegration()],\
              });\
            };\
            window.testSentry = function() { Module.wasmTable.get(99999)(); };\
          </script>\
          <script src="https://cdn.jsdelivr.net/npm/@sentry/wasm@10.45.0/build/bundle.min.js" crossorigin="anonymous"></script>\
          <script src="https://cdn.jsdelivr.net/npm/@sentry/browser@10.45.0/build/npm/cjs/prod/index.min.js" crossorigin="anonymous"></script>\
          ' handheld/project/web/web_shell.html

      - name: Build
        run: |
          mkdir -p handheld/build/web
          emcmake cmake -S handheld/project/web -B handheld/build/web -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-g"
          cmake --build handheld/build/web -j$(nproc)

      - name: Setup sentry-cli
        uses: matbour/setup-sentry-cli@v2

      - name: Download wasm-split
        uses: robinraju/release-downloader@v1
        with:
          repository: 'getsentry/symbolicator'
          latest: true
          fileName: 'wasm-split-Linux-x86_64'
          out-file-path: '/usr/local/bin/wasm-split'
        run: |
          chmod +x /usr/local/bin/wasm-split

      - name: Split WASM and upload debug symbols
        run: |
          wasm-split handheld/build/web/index.wasm -d handheld/build/web/index.debug.wasm --strip
          sentry-cli debug-files upload -o $SENTRY_ORG -p $SENTRY_PROJECT handheld/build/web/index.debug.wasm

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: handheld/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.1
